# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thinkapp-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SnapKit'
  pod 'RangeUISlider'
  # Pods for thinkapp-ios

end
